package com.cg.dao;

import java.util.List;

import com.cg.bean.FeedbackParameters;
import com.cg.bean.FeedbackReport;
import com.cg.exception.FeedbackNotFoundException;


public interface FeedbackReportDao {

	String byMonth = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_MASTER TM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, FEEDBACK_MASTER FM WHERE TM.FACULTY_CODE = EM.EMPLOYEE_ID AND TM.TRAINING_CODE = FM.TRAINING_CODE AND EM1.EMPLOYEE_ID = FM.PARTICIPANT_ID AND EXTRACT(MONTH FROM END_DATE)=?";
	String avgByMonth = "SELECT AVG(FB_PRS_COMM), AVG(FB_CLRFY_DBTS), AVG(FB_TM), AVG(FB_HND_OUT), AVG(FB_HW_SW_NTWRK) FROM FEEDBACK_MASTER FM, TRAINING_MASTER TM WHERE FM.TRAINING_CODE = TM.TRAINING_CODE AND EXTRACT(MONTH FROM END_DATE) = ?";
	
	String byFacultyAndMonth = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_MASTER TM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, FEEDBACK_MASTER FM WHERE TM.FACULTY_CODE = EM.EMPLOYEE_ID AND TM.TRAINING_CODE = FM.TRAINING_CODE AND EM1.EMPLOYEE_ID = FM.PARTICIPANT_ID AND EXTRACT(MONTH FROM END_DATE)=? AND TM.FACULTY_CODE = ?"; 
	String avgByFacultyAndMonth = "SELECT AVG(FB_PRS_COMM), AVG(FB_CLRFY_DBTS), AVG(FB_TM), AVG(FB_HND_OUT), AVG(FB_HW_SW_NTWRK) FROM FEEDBACK_MASTER FM, TRAINING_MASTER TM WHERE FM.TRAINING_CODE = TM.TRAINING_CODE AND EXTRACT(MONTH FROM END_DATE) = ? AND TM.FACULTY_CODE = ?";
	
	//String feedbackDefaulters = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_PARTICIPANT_MASTER TP, FEEDBACK_MASTER FM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, TRAINING_MASTER TM WHERE TP.PARTICIPANT_ID = FM.PARTICIPANT_ID(+) AND FM.PARTICIPANT_ID IS NULL AND TM.TRAINING_CODE = TP.TRAINING_CODE AND EM1.EMPLOYEE_ID = TP.PARTICIPANT_ID AND EM.EMPLOYEE_ID = TM.FACULTY_CODE AND EXTRACT(MONTH FROM END_DATE) = ?";
	String feedbackDefaulters = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_PARTICIPANT_MASTER TP, FEEDBACK_MASTER FM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, TRAINING_MASTER TM WHERE TP.TRAINING_CODE = FM.TRAINING_CODE(+) AND TP.PARTICIPANT_ID = FM.PARTICIPANT_ID(+) AND FM.PARTICIPANT_ID IS NULL AND TM.TRAINING_CODE = TP.TRAINING_CODE AND EM1.EMPLOYEE_ID = TP.PARTICIPANT_ID AND EM.EMPLOYEE_ID = TM.FACULTY_CODE AND EXTRACT(MONTH FROM END_DATE)=?";
	
	List<FeedbackReport> byMonth(int month) throws FeedbackNotFoundException;
	
	List<FeedbackReport> byFacultyForMonth(int facultyCode, int month) throws FeedbackNotFoundException;
	
	List<FeedbackReport> feedbackDefaultersByMonth(int month) throws FeedbackNotFoundException;
	
	FeedbackParameters getAvgByMonth(int month);
	
	FeedbackParameters getAvgByMonthAndFaculty(int month, int facultyCode);
	
}
